development:
  clients:
    default:
      database: game_tracker_development
      hosts:
        - localhost:27017
      options:
        username: <%= "#{ENV['MONGO_INITDB_ROOT_USERNAME']}" %>
        password: <%= "#{ENV['MONGO_INITDB_ROOT_PASSWORD']}" %>
  options:

production:
  clients:
    default:
      database: game_tracker_production
      hosts:
        - <%= "#{ENV['MONGODB_HOST']}:#{ENV['MONGODB_PORT']}" %>
      options:
        username: <%= "#{ENV['MONGO_INITDB_ROOT_USERNAME']}" %>
        password: <%= "#{ENV['MONGO_INITDB_ROOT_PASSWORD']}" %>
  options:


test:
  clients:
    default:
      database: game_tracker_test
      hosts:
        - localhost:27017
      options:
        username: <%= "#{ENV['MONGO_INITDB_ROOT_USERNAME']}" %>
        password: <%= "#{ENV['MONGO_INITDB_ROOT_PASSWORD']}" %>
        read:
          mode: :primary
        max_pool_size: 1
